### ISSUE TITLE
Error Catching for Retry Logic for Logger

### ISSUE THREAD

**Issue by lazyplatypus** [newrelic-experimental/gatsby-plugin-newrelic#1]
The issue here is that a number of steps repeatedly log to the console to show the `⠋` type loading pattern, which results in repeated unnecessary requests to the logging endpoint. This is timing out presumably due to rate limiting or something like that. The best option here is to only send those log messages once, as repeated logs is completely unnecessary

**Comment by rudouglas** [comment]
This is also resolved as part of `1.0.8` where we only log a single message for those repeated log messages
