### ISSUE TITLE
Determine type of commit based on data change

### ISSUE THREAD

**Issue by lazyplatypus** [newrelic-experimental/gatsby-plugin-newrelic#4]
We need to determine if a commit is 
- [ ] A data change from a content management system (just data, no code)
- [ ] Cached Code Change (taking advantage of incremental builds)
- [ ] Uncached code change (reg build)

**Comment by rudouglas** [comment]
Do we just want to look for changes like this:

The cache is also invalidated by Gatsby in a few cases, specifically:

- If package.json changes, for example a dependency is updated or added
- If gatsby-config.js changes, for example a plugin is added or modified
- If gatsby-node.js changes, for example if you invoke a new Node API, or change a createPage call

**Comment by rudouglas** [comment]
I went with parsing the log messages for the moment, this tells us:

 - `clearedCache: {Boolean}`
 - `deletedPages: {int}`
 - `changedPages: {int}`
