### ISSUE TITLE
Too many things are getting logged - we should have logic to check for redundancy and send less logs plz

### ISSUE THREAD

**Issue by lazyplatypus** [newrelic-experimental/gatsby-plugin-newrelic#8]
![Screen Shot 2021-07-18 at 9 51 31 PM](https://user-images.githubusercontent.com/10321085/126104676-5fb25565-10fd-42f8-813d-fc4243a067f5.png)

**Comment by rudouglas** [comment]
I've added logic for this already as of `1.0.8` which checks for those logs that log multiple times and only logs them once
